templates:
    params:
        author-name: "Andrew A. Cashner"
        author-email: "andrew.cashner@rochester.edu"
        category: Music
        copyright: "Copyright © 2022 Andrew A. Cashner. All rights reserved."
        gitbuh-username: andrewacashner

source-repository head
    type: github 
    location: https://github.com/andrewacashner/arca.git
