templates:
    params:
        author-name: "Andrew A. Cashner"
        author-email: "andrew.cashner@rochester.edu"
        category: Music
        copyright: "Copyright © 2022 Andrew A. Cashner. All rights reserved."
        bitbucket-username: andrewacashner

source-repository head
    type: bitbucket
    location: https://www.bitbucket.org/andrewacashner/arca.git
