name:                arca
version:             0.1.0.0
license:             AllRightsReserved
author:              "Andrew A. Cashner"
copyright:           "Copyright © 2022 Andrew A. Cashner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            "A digital implementation of Athanasius Kircher's device for automatic music composition, the Arca musarithmica of 1650"
category:            Music

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: "Please see the README on Github at
  <https://github.com/andrewacashner/kircher/src/master/arca/README.md>.
  The arca web app is at <https://www.arca1650.info>."

dependencies:
- base      >= 4.7 
- assoc-list 
- directory
- filepath
- ilist  
- process
- random
- split
- text
- vector
- xml

library:
  source-dirs: src

executables:
  # Statically linked, self-contained binary 
  arca-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -static
    - -threaded
    - -rtsopts
    cc-options:
    - -static
    ld-options:
    - -static
    - -pthread
      #    - -fuse-ld=lld
    dependencies:
    - arca

  # Dynamically linked executable
  arca:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    dependencies:
    - arca

  # Testing version with no chance operations
  arca-nochance:
    main:               NoChance.hs
    source-dirs:        test
    dependencies:
    - arca


      #tests:
      #  arca-test:
    #    main:                Spec.hs
    #    source-dirs:         test
    #    ghc-options:
    #    - -threaded
    #    - -rtsopts
    #    - -with-rtsopts=-N
    #    dependencies:
    #    - arca
    #    - ilist
    #    - process
