name:                arca
version:             0.1.0.0
github:              "andrewacashner/arca"
license:             AllRightsReserved
author:              "Andrew A. Cashner"
maintainer:          "andrewacashner@gmail.com"
copyright:           "Copyright © 2020 Andrew A. Cashner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/arca#readme>

dependencies:
- base >= 4.7 && < 5
- vector >= 0.12.0.3
- random >= 1.1
- split >= 0.2.3.3

library:
  source-dirs: src

executables:
  arca-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arca

tests:
  arca-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arca
