name:                arca
version:             0.1.0.0
license:             AllRightsReserved
author:              "Andrew A. Cashner"
maintainer:          "andrew.cashner@rochester.edu"
copyright:           "Copyright © 2021 Andrew A. Cashner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Bitbucket at <https://bitbucket.org/andrewacashner/kircher/src/master/arca/README.md>
dependencies:
- base      >= 4.7 && < 5
- directory
- filepath
- ilist  
- process
- random
- split
- text
- vector
- xml

library:
  source-dirs: src

executables:
  arca-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arca

tests:
  arca-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arca
    - ilist
    - process
